### ISSUE TITLE
protoc-gen-ng: Incorrect generation for AsObject interfaces in *.pb.ts files

### ISSUE THREAD

**Issue by slydor** [ngx-grpc/ngx-grpc#75]
Hi, thank you for this cool plugin protoc-gen-ng, we use it in our Angular app to abstract all the low level gRPC stuff from the business logic layers, and it works quite well!

Also, we use the AsObject interfaces to assert correct types/shape of mock data by binding request and response parameter to those types for our mock server (written in node/TS using @grpc/grpc-js).

```ts
import { Server } from '@grpc/grpc-js';
import { handleUnaryCall } from '@grpc/grpc-js';
import { SnakeCasedPropertiesDeep } from 'type-fest';
import * as resource from './generated/resource.pb';

type handleSnakyUnaryCall<Request, Response> = handleUnaryCall<
  SnakeCasedPropertiesDeep<Request>,
  SnakeCasedPropertiesDeep<Response>
>;

const listResources: handleSnakyUnaryCall<resource.ListResourcesRequest.AsObject, resource.ListResourcesResponse.AsObject> = (
  requestData,
  callback
) => { /* ... */ }

const addResourceServices = (server: Server): void => {
  const protoFileName = 'resource.proto';
  const descriptor = (getProtoDescriptorByProtoPath(protoFileName) as MakeService<'Resource'>).resource;
  server.addService(descriptor.ResourceService.service, {
    listResources,
    /* ... */
  });
};

/* then it's added to the Server instance */
```

But in the generation for proto maps I found an issue. So let's look at the generated maps.pb.ts in this repository (around line 460 in the generated file):

```ts
export module MessageWithMap {
  /**
   * Standard JavaScript object representation for MessageWithMap
   */
  export interface AsObject {
    mapStringString?: { [prop: string]: string };
    mapStringMsg?: { [prop: string]: MapSubMessage };
    mapStringBytes?: { [prop: string]: Uint8Array };
  }
```
The type of `mapStringMsg` should be `{ [prop: string]: MapSubMessage.AsObject };`, because `MapSubMessage` is the class itself. I am not sure, if this would also be desirable for the 'AsProtobufJSON' helper, but I think so. So basically, nested types are not resolved for these helpers.

To reproduce:

I just cloned the repo and after `npm install` I called
```sh
$(pwd)/node_modules/.bin/grpc_tools_node_protoc --plugin=protoc-gen-ng=$(pwd)/dist/protoc-gen-ng/main.js --ng_out=config=packages/protoc-gen-ng/ngx-grpc.conf.js:packages/protoc-gen-ng/test/out -I packages/protoc-gen-ng/test/proto $(find ./packages/protoc-gen-ng/test/proto
-iname "*.proto")
```

**Comment by smnbbrv** [comment]
The issue is fixed in v3.0.0, see [CHANGELOG](https://github.com/ngx-grpc/ngx-grpc/blob/master/CHANGELOG.md#300-2022-03-01) for details

**Comment by slydor** [comment]
Hi @smnbbrv,
in current v3.0.1 this issue is still not fixed. I'm sorry for taken that long to respond, but we needed to upgrade Angular first :)

To reproduce:
- clone repo
- `npm i`
- `mkdir ./packages/protoc-gen-ng/test/out`
- `$(pwd)/node_modules/.bin/grpc_tools_node_protoc --plugin=protoc-gen-ng=$(pwd)/dist/protoc-gen-ng/main.js --ng_out=config=packages/protoc-gen-ng/ngx-grpc.conf.js:packages/protoc-gen-ng/test/out -I packages/protoc-gen-ng/test/proto $(find ./packages/protoc-gen-ng/test/proto -iname "*.proto")`
- See file `packages/protoc-gen-ng/test/out/maps.pb.ts` line 455

In https://github.com/ngx-grpc/ngx-grpc/commit/c1a86a6eebeae3e28da1cde30527ee7488ee5d2c it passes some options, are we supposed to configure this somehow, that nested `AsObject` types are used?

**Comment by oco2000** [comment]
Hi @smnbbrv, do you accept PRs, maybe we can try to fix this?

**Comment by smnbbrv** [comment]
Hi @oco2000 

of course
